name: ai_env
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - bzip2=1.0.8
  - ca-certificates=2021.5.30
  - certifi=2021.5.30
  - click=8.0.1
  - cycler=0.10.0
  - ffmpeg=4.3.1
  - freetype=2.10.4
  - gmp=6.2.1
  - gnutls=3.6.13
  - icu=67.1
  - kiwisolver=1.3.1
  - lame=3.100
  - ld_impl_linux-64=2.33.1
  - libblas=3.9.0
  - libcblas=3.9.0
  - libedit=3.1.20191231
  - libffi=3.3
  - libgcc-ng=9.1.0
  - libgfortran-ng=7.5.0
  - libgfortran4=7.5.0
  - libiconv=1.16
  - liblapack=3.9.0
  - libopenblas=0.3.12
  - libpng=1.6.37
  - libstdcxx-ng=9.1.0
  - lintel=1.0
  - matplotlib-base=3.2.2
  - ncurses=6.2
  - nettle=3.6
  - openh264=2.1.1
  - openssl=1.1.1k
  - pip=20.3.3
  - pyparsing=2.4.7
  - python=3.7.9
  - python_abi=3.7
  - readline=8.1
  - setuptools=52.0.0
  - sqlite=3.33.0
  - tk=8.6.10
  - tornado=6.1
  - typing_extensions=3.10.0.0
  - wheel=0.36.2
  - x264=1!152.20180806
  - xz=5.2.5
  - zlib=1.2.11
  - pip:
    - argon2-cffi==20.1.0
    - async-generator==1.10
    - attrs==20.3.0
    - backcall==0.2.0
    - bleach==3.2.3
    - cffi==1.14.4
    - chardet==3.0.4
    - chart-studio==1.1.0
    - decorator==4.4.2
    - defusedxml==0.6.0
    - entrypoints==0.3
    - future==0.17.1
    - idna==2.8
    - imageio==2.9.0
    - imgaug==0.4.0
    - importlib-metadata==3.4.0
    - ipykernel==5.4.3
    - ipython==7.19.0
    - ipython-genutils==0.2.0
    - ipywidgets==7.5.1
    - jedi==0.18.0
    - jinja2==2.11.3
    - joblib==1.0.1
    - jsonschema==3.2.0
    - jupyter==1.0.0
    - jupyter-client==6.1.11
    - jupyter-console==6.2.0
    - jupyter-core==4.7.1
    - jupyterlab-pygments==0.1.2
    - markupsafe==1.1.1
    - matplotlib==3.3.0
    - mistune==0.8.4
    - nbclient==0.5.1
    - nbconvert==6.0.7
    - nbformat==5.1.2
    - nelson==0.4.3
    - nest-asyncio==1.5.1
    - networkx==2.5
    - notebook==6.2.0
    - numpy==1.20.1
    - open3d-python==0.7.0.0
    - opencv-python==4.5.3.56
    - packaging==20.9
    - pandas==1.2.3
    - pandocfilters==1.4.3
    - parso==0.8.1
    - patsy==0.5.1
    - pexpect==4.8.0
    - pgmpy==0.1.10
    - pickleshare==0.7.5
    - pillow==8.1.0
    - plotly==4.14.3
    - prometheus-client==0.9.0
    - prompt-toolkit==3.0.14
    - ptyprocess==0.7.0
    - pycparser==2.20
    - pygments==2.7.4
    - pyrsistent==0.17.3
    - python-dateutil==2.8.1
    - pytz==2020.5
    - pywavelets==1.1.1
    - pyyaml==5.4.1
    - pyzmq==22.0.2
    - qtconsole==5.0.2
    - qtpy==1.9.0
    - requests==2.22.0
    - requests-toolbelt==0.9.1
    - retrying==1.3.3
    - scikit-image==0.18.2
    - scikit-learn==0.24.2
    - scipy==1.6.1
    - seaborn==0.11.1
    - send2trash==1.5.0
    - shapely==1.7.1
    - six==1.15.0
    - sklearn==0.0
    - statsmodels==0.12.2
    - terminado==0.9.2
    - testpath==0.4.4
    - threadpoolctl==2.1.0
    - tifffile==2021.7.2
    - torch==1.4.0
    - torchvision==0.5.0
    - tqdm==4.58.0
    - traitlets==5.0.5
    - typing-extensions==3.7.4.3
    - urllib3==1.25.11
    - wcwidth==0.2.5
    - webencodings==0.5.1
    - widgetsnbextension==3.5.1
    - zipp==3.4.0

